import Features from "../components/Features";
import Hero from "../components/Hero";
import Howit from "../components/Howit";
import Script from 'next/script'
import Faq from "../components/Faq";
import Footer from "../components/Footer";
import Navigation from "../components/Navigation";
import Head from 'next/head';
import Services from "../components/Services";


export default function Home() {
    return (
        <div>
            <Head>
                <title>Sakarya Web | yigitersalman.com.tr</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo1.png" />
                <meta name="keywords" content="web tasarım,sakarya web tasarım,hosting,domain,sunucu,yiğiter salman,yiğiter,salman,web tasarım,web design,hendek web,sakarya web,yigiter,e-ticaret,e-ticaret sakarya,e-ticaret hendek,e ticaret,hendek web tasarım,wordpress" />
                <meta name="robots" content="index, follow" />
            </Head>
            <Navigation></Navigation>
            <Hero></Hero>
            <Howit></Howit>
            <Features></Features>
            <Services></Services>
            <Faq></Faq>
            <Footer></Footer>
            <Script src="/script.js"></Script>
        </div>
    )
}